apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-admin
  template:
    metadata:
      labels:
        app: flask-admin
    spec:
      containers:
      - name: flask-admin
        image: $DOCKERHUB_USERNAME/python-flask-admin:latest
        ports:
        - containerPort: 5000
